### ISSUE TITLE
fix: using a project w/ Laravel sail shows File permission issues

### ISSUE THREAD

**Issue by MikeCraig418** [VemtoOrg/vemto2-issues#1]
**OS:** Mac M1  
**Docker:** Yes

**Steps to Reproduce:**

*   I "connected" to an existing project, which uses Laravel sail
*   Upon opening, the error below is displayed

![](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/23151962/3d1a75db-1d81-4655-8fb3-314a70e9d0a5)

This error can be resolved by shutting down Laravel sail and launching the application once more.

**Comment by TiagoSilvaPereira** [comment]
@yo-mike please try Vemto 2.0.2. It is necesssary to delete the .vemto folder and connect again
