### ISSUE TITLE
(error) FAILED to execute command: "C:\laragon\bin\php\php-8.2.12-nts-Win32-vs16-x64\php.exe" artisan jetstream:install livewire --no-interaction

### ISSUE THREAD

**Issue by Flat-Duck** [VemtoOrg/vemto2-issues#100]
**Error Message:**
(error) FAILED to execute command: "C:\laragon\bin\php\php-8.2.12-nts-Win32-vs16-x64\php.exe" artisan jetstream:install livewire --no-interaction

**Stack:**
```
Error: Command failed: "C:\laragon\bin\php\php-8.2.12-nts-Win32-vs16-x64\php.exe" artisan jetstream:install livewire --no-interaction

    at ChildProcess.exithandler (node:child_process:407:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

---

Vemto 2.0.8
win32 10.0.22631
Locale: en-US
App version: 2.0.8

**Comment by TiagoSilvaPereira** [comment]
@Flat-Duck, could you please provide more details so that I can reproduce this issue? What steps did you take until the error occurred?

**Comment by Flat-Duck** [comment]
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/7350041/7610f42b-70dd-470d-ac1b-8e94a4aa36a7)

i just filled the fields and hit create app it took some time then after saying installing Jetstream it broke and gave this error

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/7350041/27ca8728-07ac-4ee2-9e6a-adf3499f8bed)

**Comment by TiagoSilvaPereira** [comment]
@Flat-Duck, thanks for sending the details. Does this problem happens when executing artisan jetstream:install livewire --no-interaction from your command line?

**Comment by TiagoSilvaPereira** [comment]
@Flat-Duck closing for now, please try with Vemto 2.0.10.
