### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by markdueck** [VemtoOrg/vemto2-issues#101]
**Error Message:**
Unknown Error

**Stack:**
```
schema-reader Error: #0 phar:///tmp/.mount_Vemto-oaL4fs/resources/static/VMTTL2/index.php(80): VemtoDBReader\DatabaseManager->dropDatabase()
#1 phar:///tmp/.mount_Vemto-oaL4fs/resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#2 phar:///tmp/.mount_Vemto-oaL4fs/resources/static/VMTTL2/index.php(18): Vemto\Vemto::execute()
#3 /tmp/.mount_Vemto-oaL4fs/resources/static/VMTTL2(15): require('...')
#4 {main}
```

---

Vemto 2.0.8
linux 6.5.0-28-generic
Locale: en-US
App version: 2.0.8

**Comment by markdueck** [comment]
I'm just getting started with this.  maybe this is an easy fix, so please help me if you can.  Thanks.

**Comment by TiagoSilvaPereira** [comment]
@markdueck is this a new project or an existing one? Could you please try creating a new project with Vemto? Or maybe creating a new project manually then connecting it to Vemto?

**Comment by markdueck** [comment]
it was a new project I had just created using laravel new -  <new app name> 
I tried creating with vemto, but it caused an error:
(error) FAILED to execute command: /usr/local/bin/composer create-project laravel/laravel:^11.0 VemtoLara
Error: spawn /bin/sh ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
    
    I executed that exact same command on a command line, and it works without issues.  
    
I then created the folder I had set in the Project Path, then it ran and created another folder inside the Project Path folder with the Project name.   (  maybe I'm just being particular, but explaining what I would have expected.)  It then failed when trying to install filament, because I had a missing extension (zip).   I installed the extension, ran the filament install from command line, not Vemto - it completed.
- I then recreated all using Vemto and it worked, but when trying to connect to the database, it does not work.  I'm using Postgresql.  Is that not supported? 

-- so 2 points I think would be a good adjustment to Vemto. 1. check if these extensions exist before running.  2. not create another folder inside the project path for the project.  I'd assume the project would be the project path, not a subdirectory deeper.

**Comment by TiagoSilvaPereira** [comment]
Hi @markdueck thank you for your detailed response. PostgreSQL support is coming in the next version (already working; we just need to fix some minor bugs). Also, soon we'll add a better way to identify missing dependencies before trying to run commands

**Comment by markdueck** [comment]
Thank you @TiagoSilvaPereira for being open to receive suggestions.  I was afraid I had said too much.   I'll wait for the update that will fully support Postgresql and test at that time again. 
Thanks.

**Comment by TiagoSilvaPereira** [comment]
My pleasure @markdueck detailed feedbacks are gold because it facilitates me to identify where I need to improve Vemto

**Comment by TiagoSilvaPereira** [comment]
@markdueck fixed, now Vemto supports PostgreSQL correctly and shows all extensions you need to install

**Comment by markdueck** [comment]
@TiagoSilvaPereira  Thank you.  Much Appreciated.
