### ISSUE TITLE
unable to open an old project

### ISSUE THREAD

**Issue by MCS-Technology** [VemtoOrg/vemto2-issues#11]
After Connecting Folder it stuck on "Connecting...." see picture below
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/106679835/82dc9030-9130-469f-9e60-d33a5257eccf)

I deleted the .vemto folder and redid the operation and it's the same thing

**Comment by MCS-Technology** [comment]
It took a lot of time and finally he opened the project, but the diagram is not well exposed, the tables are piled up

**Comment by TiagoSilvaPereira** [comment]
@MCS-Technology, how much time does it take to open the project? How many tables does the project have?

Also, Vemto piles the tables in the same position; I'll improve this in the future, but I think this is not a bug. You can easily reorder the tables however you want.

Best regards,
Tiago

**Comment by MCS-Technology** [comment]
@TiagoSilvaPereira hi, 

It took more than 5 minutes the first time, but then it opens in the blink of an eye.

And i gree with you it's not a bug, i will reorder the 22 tables.

Best regards.
