### ISSUE TITLE
conflicting `TIP: it seems like there are errors in the schema reader. Maybe you want to use the Database Schema Reader mode` when Mode is set to "Database"

### ISSUE THREAD

**Issue by MikeCraig418** [VemtoOrg/vemto2-issues#111]
**Suggestion:**

- [ ] Omit this tip if it conflicts with the current reader mode

<img width="1348" alt="image" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/23151962/7114a27d-25a6-4dbb-8dc9-cf5318b9878d">

**Comment by TiagoSilvaPereira** [comment]
@yo-mike thanks for your suggestion

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.0.10
