### ISSUE TITLE
Filament resources creation error

### ISSUE THREAD

**Issue by ST21032020** [VemtoOrg/vemto2-issues#113]
When generating filament code if the model name is something like crm_source_types, the filament resource uses the name of the object with spaces, eg Crm Source Types, which then makes the parser throw an error and break the code generation. In this case, the class name which the code generator incorrectly generates is ViewCrm Source Type.

Hope this helps, it is clearly an easy fix.

**Comment by TiagoSilvaPereira** [comment]
Hi @ST21032020 thanks for reporting.

Pinging @nicollassilva

**Comment by TiagoSilvaPereira** [comment]
@ST21032020 could you please check if this error still exists on 2.0.10?

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.0.15
