### ISSUE TITLE
schema-reader-db Error: Failed opening required '/Users/hua/Herd/Ptech/bootstrap/app.php' (include_path='.:')

### ISSUE THREAD

**Issue by NoChizPlz** [VemtoOrg/vemto2-issues#117]
**Error Message:**
schema-reader-db Error: Failed opening required '/Users/hua/Herd/Ptech/bootstrap/app.php' (include_path='.:')

**Stack:**
```
schema-reader-db Error: #0 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#1 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(18): Vemto\Vemto::execute('schema-reader-d...', Object(Closure))
#2 /Applications/Vemto.app/Contents/Resources/static/VMTTL2(15): require('phar:///Applica...')
#3 {main}
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.0.9
darwin 23.4.0
Locale: en-US
App version: 2.0.9

**Comment by TiagoSilvaPereira** [comment]
thank you for reporting, I fixed it on 2.0.10
