### ISSUE TITLE
schema-reader-mg Error: Failed opening required '/home/xxx/tmp/melo/bootstrap/app.php' (include_path='.:/usr/share/php')

### ISSUE THREAD

**Issue by bashman** [VemtoOrg/vemto2-issues#118]
**Error Message:**
schema-reader-mg Error: Failed opening required '/home/xxx/tmp/melo/bootstrap/app.php' (include_path='.:/usr/share/php')

**Stack:**
```
schema-reader-mg Error: #0 phar:///tmp/.mount_Vemto-akbIcK/resources/static/VMTTL1/common/Vemto.php(111): {closure}()
#1 phar:///tmp/.mount_Vemto-akbIcK/resources/static/VMTTL1/index.php(23): Vemto\Vemto::execute()
#2 /tmp/.mount_Vemto-akbIcK/resources/static/VMTTL1(15): require('...')
#3 {main}
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.0.9
linux 6.5.0-28-generic
Locale: es-419
App version: 2.0.9

**Comment by TiagoSilvaPereira** [comment]
thank you for reporting, I fixed it on 2.0.10
