### ISSUE TITLE
schema-reader-db Error

### ISSUE THREAD

**Issue by JeffreyAReyes** [VemtoOrg/vemto2-issues#119]
An error after creating project.

schema-reader-db Error: Failed opening required 'D:\Projects\Programming\Vemto\simplefinance\bootstrap/../routes/app.php' (include_path='.;C:/laragon/etc/php/pear')

.....

Vemto Version: 2.0.9
OS: Windows 11

**Comment by TiagoSilvaPereira** [comment]
thank you for reporting, I fixed it on 2.0.10

**Comment by vimitali368** [comment]
Try to upgrade to version 2.0.10, I have the same error gone.
