### ISSUE TITLE
Error after loading an existing project

### ISSUE THREAD

**Issue by juliangums** [VemtoOrg/vemto2-issues#12]
<img width="710" alt="Screenshot 2024-03-12 at 17 51 11" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/22907521/c8a6a8f2-1d5e-467a-a989-4e85265a24a9">

**Comment by TiagoSilvaPereira** [comment]
@juliangums seems there is an error in the application code, please check the **getLocalKeyName()** as it shows in the error

**Comment by TiagoSilvaPereira** [comment]
@juliangums did you manage to fix this? What Laravel version is your project? Is it running with a new project?

**Comment by juliangums** [comment]
@TiagoSilvaPereira It is an existing Laravel 10 project using BelongsToThrough relationships from https://github.com/staudenmeir/belongs-to-through. I didn't manage to fix this. I don't really know where to start. It does not seem to be an application error. The code runs smoothly with no errors otherwise.

**Comment by juliangums** [comment]
updated to laravel 11 and the newest vemto version and this seems to be resolved now

**Comment by juliangums** [comment]
looked like this was just masked by another error that happened during upgrade. after fixing that, this comes back

**Comment by juliangums** [comment]
@TiagoSilvaPereira maybe for now you could just ignore any custom relation types?

**Comment by TiagoSilvaPereira** [comment]
@juliangums yes, I'll do that... I'm currently rewriting the schema reader

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.0.7
