### ISSUE TITLE
schema-reader-mg Error: SQLSTATE[HY000] [2002] No such file or directory (Connection: mysql, SQL) - When set to Migration Mode

### ISSUE THREAD

**Issue by christiantraets** [VemtoOrg/vemto2-issues#125]
**Error Message:**
schema-reader-mg Error: SQLSTATE[HY000] [2002] No such file or directory (Connection: mysql, SQL: select * from `suppliers` order by `created_at` asc limit 100 offset 0)

**Stack:**
```
schema-reader-mg Error: #0 /Users/*/Sites/*/vendor/laravel/framework/src/Illuminate/Database/Connection.php(967): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
[..]
```

---

Vemto 2.0.10
darwin 23.4.0
Locale: nl
App version: 2.0.10

Schema Reader Option: Migration

**Comment by TiagoSilvaPereira** [comment]
Hi @christiantraets is this a new project or an existing one? Could you please check if this is related?

https://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory

**Comment by christiantraets** [comment]
Project is few weeks old (fresh start with Laravel 11). 

the problem started after updating from previous update of Vemto

**Comment by TiagoSilvaPereira** [comment]
@christiantraets does it work when using the database reader? Does this problem happen with new projects?

**Comment by christiantraets** [comment]
I found the solution in the Stackoverflow article. This was the solution:

> Change "DB_HOST" in the .env file from "localhost" to "127.0.0.1"
