### ISSUE TITLE
schema-reader-db Error: Could not drop database `vemto_schema_reader`: SQLSTATE[HY000]: General error: 3681 Schema 'vemto_schema_reader' does not exist, but schema directory '.\vemto_schema_reader\' was found. This must be resolved manually (e.g. by moving the schema directory to another location).

### ISSUE THREAD

**Issue by vimitali368** [VemtoOrg/vemto2-issues#129]
**Error Message:**
schema-reader-db Error: Could not drop database `vemto_schema_reader`: SQLSTATE[HY000]: General error: 3681 Schema 'vemto_schema_reader' does not exist, but schema directory '.\vemto_schema_reader\' was found. This must be resolved manually (e.g. by moving the schema directory to another location).

**Stack:**
```
schema-reader-db Error: #0 phar://C:/Users/w11.vemto/AppData/Local/Programs/Vemto2/resources/static/VMTTL2/index.php(94): VemtoDBReader\DatabaseManager->dropDatabase('vemto_schema_re...')
#1 phar://C:/Users/w11.vemto/AppData/Local/Programs/Vemto2/resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#2 phar://C:/Users/w11.vemto/AppData/Local/Programs/Vemto2/resources/static/VMTTL2/index.php(18): Vemto\Vemto::execute('schema-reader-d...', Object(Closure))
#3 C:\Users\w11.vemto\AppData\Local\Programs\Vemto2\resources\static\VMTTL2(14): require('phar://C:/Users...')
#4 {main}
```

---

Vemto 2.0.11
win32 10.0.25262
Locale: ru
App version: 2.0.11

**Comment by vimitali368** [comment]
It is a new project.
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/3a0abd50-90d4-41ee-87c7-6a3aae54b156)

**Comment by vimitali368** [comment]
It seems that instead of connecting MySQL, the program is trying to use the Sqlite connection, this is confirmed by the commented connection settings lines:
.env
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
#DB_PORT=981
#DB_DATABASE=v2011_test2
#DB_USERNAME=root
#DB_PASSWORD=

**Comment by vimitali368** [comment]
If instead of "Database - Read from a database", change "Migration - Read from migrations files", project will be open.

**Comment by vimitali368** [comment]
Reinstalling did not give any result. I will try again to install a clean VM, environment and Vemto.

**Comment by TiagoSilvaPereira** [comment]
Hi @vimitali368 Vemto uses .vemto_settings file to connect to the database, not the .env file. It seems this issue is related to some MySql 8+ issues:

https://stackoverflow.com/questions/58454272/mysql-8-0-create-new-db-schema-directory-already-exists

**Comment by vimitali368** [comment]
The problem was with the database. The vemto_schema_reader directory in the data\mysql-8\ folder remains from previous installations. Manually deleting this directory helped.

**Comment by TiagoSilvaPereira** [comment]
@vimitali368 thanks; I'll add a tip to this on the error page
