### ISSUE TITLE
schema-reader-mg Error: Failed opening required '/**/bootstrap/app.php' (include_path='.:')

### ISSUE THREAD

**Issue by aldoyh** [VemtoOrg/vemto2-issues#130]
**Error Message:**
schema-reader-mg Error: Failed opening required '**//BahrainSummit/bootstrap/app.php' (include_path='.:')

**Stack:**
```
schema-reader-mg Error: #0 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/common/Vemto.php(111): {closure}()
#1 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(23): Vemto\Vemto::execute('schema-reader-m...', Object(Closure))
#2 /Applications/Vemto.app/Contents/Resources/static/VMTTL1(15): require('phar:///Applica...')
#3 {main}
```

**How to reproduce:**
1. Checked app update, started new project.
2. configured quick full meal of everything.
3. then -> 
![Screenshot 2024-05-11 at 06 11 32](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/5215449/6122eea6-5b57-467d-b8c1-7b5b4e96735d)

**Expected behavior:**
No error.

**Additional context:**
I have been using vemto on my M1 Max MBP since the earliest days, yes it worked like a Spell 🪄 .. Once only.
then any new project does cost issues with folder permission or files somehow.

Let's have a good ride in the new wheels 🛞 and feedback soon. ❤️ 

---

Vemto 2.0.9
darwin 23.4.0
Locale: en-US
App version: 2.0.9

**Comment by TiagoSilvaPereira** [comment]
Hi @aldoyh, please upgrade to 2.0.12; version 2.0.9 introduced this weird bug that was fixed on 2.0.10 one week ago. Best regards,
Tiago
