### ISSUE TITLE
When the button is pressed "Open Project on Command Line (F7)" - Not found

### ISSUE THREAD

**Issue by vimitali368** [VemtoOrg/vemto2-issues#131]
Get an error: "Can't find wt.exe. Check if the name is correct and try again"
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/e183161c-5742-4200-b8cd-7c932f9801e3)

It may be possible to make a custom command-line application to specify the path to the file. For example, I use the Cmder program

**Comment by TiagoSilvaPereira** [comment]
Hi @vimitali368 thank you for your suggestion. For now, you can install Windows Terminal: https://apps.microsoft.com/detail/9n0dx20hk701?hl=pt-br&gl=US

**Comment by TiagoSilvaPereira** [comment]
Also, I'll close this for now. Just setting the path may not work because each terminal has its way of starting up from a path (so it would be necessary to create a separate code for each terminal type). For now, it is better to just install Windows Terminal if you are on Windows.

**Comment by vimitali368** [comment]
I have installed Windows Terminal so far. Thanks
