### ISSUE TITLE
The APP menu and the filament resources are not generated

### ISSUE THREAD

**Issue by vimitali368** [VemtoOrg/vemto2-issues#133]
After generating the code. I run the "npm run build" commands. "php artisan serve". But the application menu does not appear.
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/0469fd62-8282-4ef4-bfcc-a9ab90b84a01)

**Comment by vimitali368** [comment]
Here are my settings:
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/6e449d15-779f-405c-967d-8dc0f58b3323)
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/b9d3c79a-0b3b-44ee-ac06-a069f85c5acf)
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/3c804adc-da71-4745-b80a-7e821a642f7f)
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/35c5935e-5ad3-4ab2-8e58-d0a14e762abb)

**Comment by TiagoSilvaPereira** [comment]
@vimitali368 please check files with conflicts (probably app.layout.blade was not generated due to a conflict)

**Comment by vimitali368** [comment]
After press button "Generate code", I take this message:
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/633f9846-165a-4651-8e39-3da136c6e182)

**Comment by vimitali368** [comment]
Routes are created and work:
 GET|HEAD  dashboard ...................
 GET|HEAD  dashboard/projects ..........
 GET|HEAD  dashboard/projects/create ...
 GET|HEAD  dashboard/projects/{project} 
 GET|HEAD  dashboard/users .............
 GET|HEAD  dashboard/users/create ......
 GET|HEAD  dashboard/users/{user} ......

**Comment by vimitali368** [comment]
http://127.0.0.1:8000/dashboard/users
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/3bd0fde8-464a-47be-9a2f-48317bdad663)

**Comment by TiagoSilvaPereira** [comment]
@vimitali368 Please check for conflicts on the Files Queue:

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/82a83a17-918d-4a0a-bd39-6bdd4dd1f085)

It is very common to have conflicts with the app.blade.php file (or layout.blade.php).

In future Vemto versions, I'll change them to avoid having conflicts if this is a newly created application. But for now, Vemto generates a conflict (because those files already exist), and you need to solve them manually (you can accept the Vemto-generated version or merge the code if necessary). For files you don't want to solve conflicts, instruct Vemto to ignore them.

**Comment by vimitali368** [comment]
There are no conflicts:
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/d76a7fe4-eda8-4254-acb4-473b4d743d82)

> app.layout.blade
There is no such file.
In file "\resources\views\navigation-menu.blade.php" the "App" item is missing.

**Comment by vimitali368** [comment]
Since this is a new project, I can share a project or folder ".vemto"

**Comment by TiagoSilvaPereira** [comment]
@vimitali368 please check if both those files were rendered:

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/189f7adc-77c6-4fb7-bf49-df7255c0bff2)

And if app.layout.php has the following line of code:

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/8eb392b6-fb52-4927-a7f8-024a9792495f)

**Comment by vimitali368** [comment]
I created the same project from scratch on Vento version 2.0.12.
When generating, I get an error:
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/14663e14-023a-4005-80d8-8e1b21027ef7)

**Comment by vimitali368** [comment]
These three files had the attributes "Read-only" and "Archived". By removing these attributes, the generation was successful.

**Comment by vimitali368** [comment]
Now the result is obtained:
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/06915687-2e3e-4817-96b0-9445ef4a7e47)
But also have black menu, how in ticket https://github.com/TiagoSilvaPereira/vemto2-issues/issues/114
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/ed38a576-dd4a-4ee3-bd86-3fd9c2c11700)

**Comment by vimitali368** [comment]
The dark theme is related to the Windows theme settings. After selecting a light theme in Windows, the theme of the top menu of the web application has also changed.
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/c6bdc37f-aaea-4f25-842e-c4457a5f4b2e)

**Comment by TiagoSilvaPereira** [comment]
@vimitali368 Perfect. I'm closing this for now, as the issue has been solved. Also, please upgrade to 2.0.13 to avoid permission issues. Please feel free to open other issue or reopen if necessary
