### ISSUE TITLE
wrong folder permission on fresh project

### ISSUE THREAD

**Issue by t0nka** [VemtoOrg/vemto2-issues#134]
vemto 2.0.12
OS: macOS 14.4.1 (23E224)

1.) create a new, fresh project

<img width="728" alt="image" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/4823546/065fbc02-a903-4cfb-9c0e-74692e13f061">

2.) open finder
the fresh generate folder permission is wrong:
/**resources** is now 644 (not writeable)
<img width="1068" alt="image" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/4823546/abd82833-04b3-40cf-81e5-73e64bd814b4">

fyi: /public is correct 755
<img width="1062" alt="image" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/4823546/634cb20f-ec36-4114-93c1-adb2b1b9c715">

**Comment by t0nka** [comment]
/resources/views is also 644

**Comment by t0nka** [comment]
/resources/views/components is also 644

**Comment by t0nka** [comment]
/resources/views/components/layouts is also 644

**Comment by TiagoSilvaPereira** [comment]
Hi @t0nka thank you very much for reporting. I'm closing so that we can continue the conversation on #97

**Comment by TiagoSilvaPereira** [comment]
Hi @t0nka thanks for reporting.

Adding useful information from #97

**Comment by t0nka** [comment]
I created a fresh and empty Project. No Models No Forms No apps

**Comment by TiagoSilvaPereira** [comment]
@t0nka does this problem happen when creating a project with Breeze instead of Jetstream?

**Comment by t0nka** [comment]
same error with breeze

**Comment by TiagoSilvaPereira** [comment]
@t0nka please check the new version 2.0.13, if the problem persists

**Comment by t0nka** [comment]
@TiagoSilvaPereira problem fixed in 2.0.13 macOs.
