### ISSUE TITLE
Bug - Unable to save changes to a model

### ISSUE THREAD

**Issue by TheITJuggler** [VemtoOrg/vemto2-issues#136]
Platform: 
- Mac OS 14.4.1 on Macbook M1 (arm)
- Vemto 2.0.13

Easy Steps to Reproduce:
- Create a new app
<img width="876" alt="Screenshot 2024-05-17 at 16 03 04" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1438462/e1ab35df-c992-4346-807d-6ecf0760365e">
<img width="1063" alt="Screenshot 2024-05-17 at 16 03 58" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1438462/95709022-c21d-4304-9261-2122cfb12a15">

- edit the users model, and enable soft-deletes
<img width="802" alt="Screenshot 2024-05-17 at 16 06 25" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1438462/576d7818-7d33-42c3-9a36-902228737def">

- click Save on "There are schema changes"
- click "Solve Conflicts"
- select either "Solve Manually" or "Accept Generated"
- confirm you "are you sure you want to accept the generated code?"
- click "Save Changes"
- notice the following error at top of screen
<img width="484" alt="Screenshot 2024-05-17 at 15 59 16" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1438462/2118ac01-5725-46f3-b8a4-82af003e8458">

Issue was not experienced on Vemto 2.11

**Comment by TiagoSilvaPereira** [comment]
@TheITJuggler thanks for reporting

**Comment by TiagoSilvaPereira** [comment]
@TheITJuggler, also, please try to upgrade to 2.0.13, maybe this bug was already solved

**Comment by TiagoSilvaPereira** [comment]
@TheITJuggler fixed on 2.0.14
