### ISSUE TITLE
(error) FAILED to execute command: "php" "C:\Users\uVemto\AppData\Local\Programs\Vemto2\resources\static\VMTTL2"

### ISSUE THREAD

**Issue by vimitali368** [VemtoOrg/vemto2-issues#137]
**Error Message:**
(error) FAILED to execute command: "php" "C:\Users\uVemto\AppData\Local\Programs\Vemto2\resources\static\VMTTL2"

**Stack:**
```
Error: Command failed: "php" "C:\Users\uVemto\AppData\Local\Programs\Vemto2\resources\static\VMTTL2"

    at ChildProcess.exithandler (node:child_process:407:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.0.14
win32 10.0.22631
Locale: ru
App version: 2.0.14

**Comment by vimitali368** [comment]
This happens when the project is opened. The project was created by version 2.0.11. In the terminal, the command "php" "C:\Users\uVemto\AppData\Local\Programs\Vemto2\resources\static\VMTTL2 "" it's going well. The folder .vemto was deleted, it doesn't help.

**Comment by TiagoSilvaPereira** [comment]
@vimitali368, does this problem happen for all your projects? What is the result when running the command on the terminal?

**Comment by vimitali368** [comment]
In the terminal, the command "php" "C:\Users\uVemto\AppData\Local\Programs\Vemto2\resources\static\VMTTL2 "" it's going well.

**Comment by vimitali368** [comment]
When creating a new project, the code is generated.

**Comment by TiagoSilvaPereira** [comment]
> In the terminal, the command "php" "C:\Users\uVemto\AppData\Local\Programs\Vemto2\resources\static\VMTTL2 "" it's going well.

@vimitali368, what is the output of this command? What is returned when you run this on the terminal?

**Comment by vimitali368** [comment]
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/2881f071-5ad3-4155-96ca-128d5e5d5f93)

**Comment by TiagoSilvaPereira** [comment]
@vimitali368 Thanks, I'll investigate. Is this project still opening in the original 2.0.11 Vemto version?

**Comment by vimitali368** [comment]
So far in 2.0.11 I get the same error:
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/c602c0a2-bb69-4e28-80dd-f0f450e280a7)

**Comment by vimitali368** [comment]
It also passes from the terminal:
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/98285500-2cf6-4536-85b1-a7f65e0ca7af)

**Comment by TiagoSilvaPereira** [comment]
@vimitali368, okay. Did you make some manual changes to this project? Could you please try dropping /vendor and running the composer install again? You could also undo changes you made to the project code to check if they are causing this problem.

**Comment by TiagoSilvaPereira** [comment]
@vimitali368 also, would it be possible tho share this project as a private Git repository?

**Comment by vimitali368** [comment]
> okay. Did you make some manual changes to this project? Could you please try dropping /vendor and running the composer install again? You could also undo changes you made to the project code to check if they are causing this problem.

Drop /vendor. composer install. There is no result.

**Comment by TiagoSilvaPereira** [comment]
Did you made changes to this project code after creating it with Vemto? If so, could you please try reverting them?

**Comment by vimitali368** [comment]
I've removed the manual edits. So far, the same result.

**Comment by TiagoSilvaPereira** [comment]
Is this also happening with new projects? Probably there is something different is this project which is causing this issue. Would it possible to share the code?

**Comment by vimitali368** [comment]
If you need a database, tell me, please.

**Comment by vimitali368** [comment]
When you download the project, please tell me so that I can delete it.

**Comment by TiagoSilvaPereira** [comment]
@vimitali368 Thanks I just downloaded it

**Comment by TiagoSilvaPereira** [comment]
@vimitali368 I just tested your project here, and I received this message. Apparently, you have a duplicate property in the SubtaskSubtaskDetail class (this is probably happening because a recursive relationship is used).

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/3f793d83-d36f-4197-a445-3339639096a0)

I don't know why the error message isn't showing up there; maybe your PHP is configured not to report errors.

You can verify this by running the code with the display_errors=on option (https://stackoverflow.com/questions/24159969/php-command-line-run-does-not-show-errors)

```
php -d display_errors=on "C:\Users\uVemto\AppData\Local\Programs\Vemto2\resources\static\VMTTL2"
```

If so, please configure your PHP installation always to report errors.

Try running the application manually; Laravel will probably report the same problem.

**Comment by vimitali368** [comment]
I deleted the Subtask model and everything related to it in my project. Deleted the folder .vemto. The project has opened. But there are problems with code generation. I'm trying to create the same clean project in Vemto 2.0.14

**Comment by TiagoSilvaPereira** [comment]
@vimitali368 perfect. Please also don't forget to enable PHP display_errors on your php.ini to avoid error messages without details. I'm closing for now. Please feel free to comment here if necessary.

**Comment by vimitali368** [comment]
I'm trying to create the same clean project in Vemto 2.0.14 There are no problems with code generation.  Perfect!!!
