### ISSUE TITLE
Column verification rule fires before completing the entry of column name

### ISSUE THREAD

**Issue by TheITJuggler** [VemtoOrg/vemto2-issues#14]
Vemto 2.0.2
New laravel 10 deployment used for testing.

In Users table, created a column 'current_company_id' type BigInt - SUCCESS
In Users table, created a column 'sms', type String. - SUCCESS
In Users table, tried to create a column named sms_verified_at - FAILURE. 

Alert pops up indicating "Column SMS already exists". This alert fires while I attempt to type the full column name.

<img width="566" alt="Screenshot 2024-03-13 at 10 35 49" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1438462/09aef1f8-c2b0-479f-aa57-f0eb03ef9972">

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.0.7
