### ISSUE TITLE
existing projects wont be opend

### ISSUE THREAD

**Issue by t0nka** [VemtoOrg/vemto2-issues#141]
os: macOs 14.4.1

i have an existing project. freshly ported to laravel 11, with no .vemto folder inside.

in vemto i choose "connect folder", select my project and klick on "open"

<img width="1029" alt="image" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/4823546/cecdd30f-9052-4595-ba95-dbbcedc93d73">

"read from migration file" is selected.
it s not a fresh laravel 11 project

when i click on "connect" , vemto **wont** **open** my project

after a vemto restart:
<img width="679" alt="image" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/4823546/a06f9411-7375-414c-8e1a-0df6e7d47030">

Database Schema Reader is shown and even won't open my project

**Comment by TiagoSilvaPereira** [comment]
@t0nka, could you please try using Database Reader? Migration Reader is just for prototypes and may have issues with existing projects

**Comment by t0nka** [comment]
same problem, wont open my project

https://github.com/TiagoSilvaPereira/vemto2-issues/assets/4823546/dbb0112e-ba33-46c2-9663-89590aee9e82

**Comment by TiagoSilvaPereira** [comment]
@t0nka is this project migrating database and running correctly? What happens when you try:

```
php artisan migrate
```

**Comment by TiagoSilvaPereira** [comment]
@t0nka please also check if https://github.com/TiagoSilvaPereira/vemto2-issues/issues/137 is related to your issue

**Comment by t0nka** [comment]
> @t0nka please also check if #137 is related to your issue

Unfortunately not working

btw. a new and fresh .vemto Folder is generated
vemto still wont open then project

**Comment by TiagoSilvaPereira** [comment]
@t0nka sorry I did not understand. Vemto is also not opening new projects?

**Comment by TiagoSilvaPereira** [comment]
@t0nka Also did you try this?

> @t0nka is this project migrating database and running correctly? What happens when you try:
> 
> ```
> php artisan migrate
> ```

I need more details about the project to understand what is happening. For example, if php artisan migrate command is not working, Vemto can't read the database structure. That is the reason I asked you to run this command.

**Comment by t0nka** [comment]
> @t0nka sorry I did not understand. Vemto is also not opening new projects?

vemto is opening complete new projects

**Comment by t0nka** [comment]
> @t0nka Also did you try this?
> 
> > @t0nka is this project migrating database and running correctly? What happens when you try:
> > ```
> > php artisan migrate
> > ```
> 
> I need more details about the project to understand what is happening. For example, if php artisan migrate command is not working, Vemto can't read the database structure. That is the reason I asked you to run this command.

yes, i tried 'php artisan migrate' - the database was already migrated. sadly nothing happend.
i can start my project with 'php artisan serv' perfectly

**Comment by TiagoSilvaPereira** [comment]
@t0nka would it be possible to share your project as a private git repository?

**Comment by t0nka** [comment]
sure - inklusive .vemto folder?

**Comment by TiagoSilvaPereira** [comment]
> sure - inklusive .vemto folder?

yes, please include .vemto folder

**Comment by TiagoSilvaPereira** [comment]
@t0nka I'm not sure why the error screen is not showing to you (please check if you have the latest Vemto version: 2.0.14). But I managed to detect the error, and I'll fix this for existing projects
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/6b77726d-9f9c-4cbd-a650-10fc1cabff15)

**Comment by t0nka** [comment]
https://github.com/TiagoSilvaPereira/vemto2-issues/assets/4823546/98b16b84-eb75-48e7-8639-588082e3d1d4

2.0.14 arm64 macOs

btw. .vemto folder added to git

**Comment by TiagoSilvaPereira** [comment]
@t0nka ok thanks! I'll fix the issues I found when trying to open your project and let you know

**Comment by TiagoSilvaPereira** [comment]
@t0nka could you please check with Vemto 2.0.15?

**Comment by t0nka** [comment]
@TiagoSilvaPereira works fine for me!
