### ISSUE TITLE
schema-reader-db Error: Could not create database `vemto_schema_reader`: SQLSTATE[HY000]: General error: 3678 Schema directory '.\vemto_schema_reader' already exists. This must be resolved manually (e.g. by moving the schema directory to another location).

### ISSUE THREAD

**Issue by vimitali368** [VemtoOrg/vemto2-issues#142]
**Error Message:**
schema-reader-db Error: Could not create database `vemto_schema_reader`: SQLSTATE[HY000]: General error: 3678 Schema directory '.\vemto_schema_reader' already exists. This must be resolved manually (e.g. by moving the schema directory to another location).

**Stack:**
```
schema-reader-db Error: #0 phar://C:/Users/uVemto/AppData/Local/Programs/Vemto2014/resources/static/VMTTL2/index.php(95): VemtoDBReader\DatabaseManager->createDatabase('vemto_schema_re...')
#1 phar://C:/Users/uVemto/AppData/Local/Programs/Vemto2014/resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#2 phar://C:/Users/uVemto/AppData/Local/Programs/Vemto2014/resources/static/VMTTL2/index.php(18): Vemto\Vemto::execute('schema-reader-d...', Object(Closure))
#3 C:\Users\uVemto\AppData\Local\Programs\Vemto2014\resources\static\VMTTL2(14): require('phar://C:/Users...')
#4 {main}
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.0.14
win32 10.0.22631
Locale: ru
App version: 2.0.14

**Comment by TiagoSilvaPereira** [comment]
@vimitali368 I'm closing as this seems not to be a Vemto issue. Please check: https://github.com/TiagoSilvaPereira/vemto2-issues/issues/129
