### ISSUE TITLE
Allow for optional foreign keys

### ISSUE THREAD

**Issue by ST21032020** [VemtoOrg/vemto2-issues#147]
Hi there, this is an enhancement, essentially, to allow for optional foreign keys.

Best!

**Comment by TiagoSilvaPereira** [comment]
Hi @ST21032020 I'm not sure I understand. What do you mean about optional foreign keys?

**Comment by TiagoSilvaPereira** [comment]
Closing due to the lack of details. please feel free to reopen or give more details

**Comment by ST21032020** [comment]
Hi there, sorry for the late reply. I was thinking of nullable foreign keys.On 27 May 2024, at 15:54, Tiago S. P. Rodrigues ***@***.***> wrote:﻿
Hi @ST21032020 I'm not sure I understand. What do you mean about optional foreign keys?

**Comment by TiagoSilvaPereira** [comment]
@ST21032020 you can mark a column as nullable here:

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/ffcda1ae-acea-4fe1-8249-e002045f5bc7)
