### ISSUE TITLE
(error) FAILED to execute command: "php" "/Applications/Vemto.app/Contents/Resources/static/VMTTL1"

### ISSUE THREAD

**Issue by adampatterson** [VemtoOrg/vemto2-issues#148]
(error) FAILED to execute command: "php" "/Applications/Vemto.app/Contents/Resources/static/VMTTL1"
    |>
Fatal error: Cannot declare class
App\Filament\Resources\CategoryResource\Pages\CreateSection, because the name is already in use in
app/Filament/Resources/SectionResource/Pages/CreateSection.php on line 9

Using Migration and Database mode both cause the same error.

**Comment by TiagoSilvaPereira** [comment]
Hi @adampatterson thanks for reporting, seems Vemto generated two classes with the same name. You can fix this by renaming one of the classes or both. I'll check a fix this

**Comment by adampatterson** [comment]
This was probably an issue on my end. it looks like I had moved some resources and it resulted in an incorrect name space.

This class didn't exist:
`App\Filament\Resources\CategoryResource\Pages\CreateSection`

but the correct namespace would have been 

`App\Filament\Resources\ SectionResource\Pages\CreateSection`

My guess is that Vemto wanted to put a class in that folder but the file already existed with the wrong namespace. 

This probably isn't a bug.

**Comment by TiagoSilvaPereira** [comment]
@adampatterson perfect! Vemto needs to boot the Laravel application to synchronize the schema. If there are duplicated classes, wrong namespaces, etc Laravel won't boot, so Vemto avoids opening the application to avoid reading inconsistent data
