### ISSUE TITLE
.vemto_settings can contain sensitive data

### ISSUE THREAD

**Issue by SlyDave** [VemtoOrg/vemto2-issues#151]
the .vemto_settings file can contain sensitive data such as the DB password and username, and the file by default is not ignored so can be included in a projects source control.

I recommend adding .vemto_settings to .gitingore as a work around, but this does mean issues sharing the vemto project.

**Comment by TiagoSilvaPereira** [comment]
Hi @SlyDave thanks for reporting, I'll change Vemto to add this to .gitignore by default (maybe create a .vemto_settings.example) with other data

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.0.24 (now Vemto adds .vemto_settings to the .gitignore and generates a .vemto_settings.example file without passwords)
