### ISSUE TITLE
adding a BelongsToMany relationship to a model in a Custom Schema places the resulting pivot table in the App Schema

### ISSUE THREAD

**Issue by MikeCraig418** [VemtoOrg/vemto2-issues#153]
When I added the relationsip to MaintenanceProcedure, I expected to see it in the MaintenanceTracker. However, it was found in the App Schema.

![](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/23151962/e091780b-df4c-4e46-9362-e50a9359b200)

![](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/23151962/b98bb430-84cb-4d8d-9d45-8db01b6f4806)

**Comment by TiagoSilvaPereira** [comment]
@yo-mike thanks for reporting

**Comment by TiagoSilvaPereira** [comment]
@MikeCraig418 fixed on 2.1.4. Thanks
