### ISSUE TITLE
Filament class names may contain errors when Name includes non PSR characters (like spaces)

### ISSUE THREAD

**Issue by MikeCraig418** [VemtoOrg/vemto2-issues#154]
**Steps To Reproduce:**

*   Generate a model like `Maintenance Procedure Site`
*   Add a Filament Resource
*   Hit the play button to generate
*   Observe the error

**Expected Behavior**

*   [ ] Class names are mutated and cleansed before adding to the PHP file

![](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/23151962/9ab475f5-9337-46c3-8082-586175d2bbb2)

![](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/23151962/17d9d306-5398-4d66-b675-37e5da1a79d3)

**Comment by nicollassilva** [comment]
Hi @yo-mike , it will be resolved soon. Thanks for your report!

**Comment by TiagoSilvaPereira** [comment]
@yo-mike Fixed on 2.0.15
