### ISSUE TITLE
schema-reader-mg Error: Failed opening required '/Users/nathanwright/Sites/ZohoFlowAPI/bootstrap/app.php' (include_path='.:')

### ISSUE THREAD

**Issue by nwconsulting** [VemtoOrg/vemto2-issues#155]
**Error Message:**
schema-reader-mg Error: Failed opening required '/Users/xxxxxxx/Sites/xxxxx/bootstrap/app.php' (include_path='.:')

**Stack:**
```
schema-reader-mg Error: #0 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/common/Vemto.php(111): {closure}()
#1 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(23): Vemto\Vemto::execute('schema-reader-m...', Object(Closure))
#2 /Applications/Vemto.app/Contents/Resources/static/VMTTL1(15): require('phar:///Applica...')
#3 {main}
```

---

Vemto 2.0.9
darwin 23.5.0
Locale: en-GB
App version: 2.0.9

**Comment by TiagoSilvaPereira** [comment]
@nwconsulting does your application have the app.php file?

**Comment by TiagoSilvaPereira** [comment]
@nwconsulting I just noticed you are using Vemto 2.0.9. Please upgrade to 2.0.15; this issue has already been solved.
