### ISSUE TITLE
Model Shows as Needing to be Saved Even After Saving

### ISSUE THREAD

**Issue by MeisamMulla** [VemtoOrg/vemto2-issues#159]
I have one model that, even when changed and saved, still shows up as needing to be saved. I can confirm that my changes are being written to the filesystem, but the message never goes away. I am unable to generate filament code as a result.

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1777638/c2fe9278-3608-4e24-9286-a778c2826565)

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1777638/9860e3ce-40d5-4be2-93a2-9e77f7bc7d98)

**Comment by TiagoSilvaPereira** [comment]
@MeisamMulla what Vemto version are you using?

**Comment by MeisamMulla** [comment]
2.0.14

I ended up recreating the table and model and it worked fine after that.

**Comment by TiagoSilvaPereira** [comment]
@MeisamMulla perfect! I think this will not happen again as I made massive improvements in the new version 2.0.15
