### ISSUE TITLE
Missing app.php file in /bootstrap folder

### ISSUE THREAD

**Issue by JeffreyAReyes** [VemtoOrg/vemto2-issues#161]
Project generated by Vemto is missing the app.php file in the /bootstrap folder.

Vemto 2.0.16
App version: 2.0.16

**Comment by JeffreyAReyes** [comment]
I tried copying the app.php file from laravel github project, and the projects runs ok. 
But subsequent code generation using the button labeled Generate Code (F5) will delete the app.php file.

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.0.17
