### ISSUE TITLE
vemto removed all files of fabrics, seeders and etc

### ISSUE THREAD

**Issue by vimitali368** [VemtoOrg/vemto2-issues#164]
When opening the file of the old project created 2.0.14, and generating the code, the files are deleted.
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/d893b52c-cafe-4d9c-b7d8-4e4163012b4e)

**Comment by vimitali368** [comment]
The same thing happens when creating a new project and creating a similar structure.

**Comment by TiagoSilvaPereira** [comment]
@vimitali368 please upgrade to 2.0.17, I just fixed this bug

**Comment by vimitali368** [comment]
Yes. upgrade to version 2.0.17, help me. But I had to regenerate the code 2 times. The files were in status "idle" for the first time.
