### ISSUE TITLE
Error: route not defined

### ISSUE THREAD

**Issue by JeffreyAReyes** [VemtoOrg/vemto2-issues#165]
I created CRUD for the users table created by Vemto during the project creation.

After login, error occurs:

Symfony\Component\Routing\Exception\RouteNotFoundException

Route [dashboard.users.index] not defined.

\resources\views\partials\app-menu.blade.php: 67

<x-slot name="content">
                @can('view-any', App\Models\User::class)
                <x-dropdown-link
                    wire:navigate
                    href="{{ route('dashboard.users.index') }}"
                >
                    {{ __('navigation.users') }}
                </x-dropdown-link>
                @endcan
            </x-slot>

Vemto 2.0.17
App version: 2.0.17

**Comment by TiagoSilvaPereira** [comment]
Hi @JeffreyAReyes please check on the Code Queue if there are conflicts with those two files and solve them before running your application:

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/79e12996-4c77-431b-9c41-ff136f0bc07a)

**Comment by TiagoSilvaPereira** [comment]
NOTE: Fix Vemto to generate bootstrap/app.php automatically when creating a new project

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.1.4
