### ISSUE TITLE
autoIncrement() being added to columns automatically causing multiple ID error

### ISSUE THREAD

**Issue by gregvarghese** [VemtoOrg/vemto2-issues#167]
Hey Tiago,

I don't know what's causing a new bug to show up. I'm updating a project I started with an earlier version of Vemto 2. I've been tweaking the tables as I go based on the new features I add. I modified columns in existing tables, but now existing integer columns are getting ->autoIncrement() added during the save function. The error causes the error below during migrations:

` 
SQLSTATE[HY000]: General error: 1 table "size" has more than one primary key 
`

I've tried removing the autoincrement in the code and syncing and unchecking it in the GUI, but it gets added back when I change something. Let me know what information I can provide to help debug!

----------

Version 2.0.18 (2.0.18)
Mac darwin 23.5.0
Locale: en-US

**Comment by gregvarghese** [comment]
Video showing part of the issue:
https://komododecks.com/recordings/nRmTXFDzgGNZknvBBQ6c?onlyRecording=1

**Comment by TiagoSilvaPereira** [comment]
@gregvarghese thanks for reporting! Does this bug happen with new projects?

**Comment by TiagoSilvaPereira** [comment]
@gregvarghese, I tried to reproduce it without success. There were a lot of changes to the internal structure from older versions, so deleting .vemto and connecting again may resolve this bug, Also please upgrade to 2.0.21 (now automatic updates are working on macOS too)

**Comment by TiagoSilvaPereira** [comment]
@gregvarghese could you please check if 2.0.22 fixes your issue?

**Comment by TiagoSilvaPereira** [comment]
@gregvarghese it seems this bug was solved (https://github.com/TiagoSilvaPereira/vemto2-issues/issues/170). Please feel free to reopen if necessary
