### ISSUE TITLE
Class "Livewire\Component" not found

### ISSUE THREAD

**Issue by hasanslaravelproject** [VemtoOrg/vemto2-issues#17]
Class "Livewire\Component" not found

  at app\Livewire\Dashboard\UserIndex.php:9
      5▕ use App\Models\User;
      6▕ use Livewire\Component;
      7▕ use Livewire\WithPagination;
      8▕
  ➜   9▕ class UserIndex extends Component
     10▕ {
     11▕     use WithPagination;
     12▕
     13▕     public $search;

  1   vendor\composer\ClassLoader.php:578

  2   vendor\composer\ClassLoader.php:432
I faced this issue. How can I solve it?

**Comment by TiagoSilvaPereira** [comment]
@hasanslaravelproject Vemto 2 does not install Livewire automatically yet. Please install Livewire manually (preferrable with Jetstream)

**Comment by TiagoSilvaPereira** [comment]
@hasanslaravelproject did installing Livewire manually fixed your issue?

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.0.7 for new projects. For existing projects, please install Livewire manually before opening it on Vemto
