### ISSUE TITLE
Vemto ad automatically "autincrement"

### ISSUE THREAD

**Issue by madesole** [VemtoOrg/vemto2-issues#170]
In the link between the tables "jobads" (HasMany) and "jobdates" (BelongsTo), the foreign key in "jobdates" is automatically set as "autoIncrement". This also happens if I add further rows of the type "TyniInteger" (e.g. days) in "jobdates".  As there are several "autincrement" in the migration, the following error is displayed when migrating table "jobdates". Even if I change the migration file manually, the "autincrement" is then added again in Vemto.

SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key (Connection: mysql, SQL: create table jobdates (id bigint unsigned not null auto_increment primary key, jobad_id bigint unsigned not null auto_increment primary key, date date not null, insertiontime varchar(255) not null, created_at timestamp null, updated_at timestamp null, deleted_at timestamp null) default character set utf8mb4 collate 'utf8mb4_0900_ai_ci')

public function up()
{
        Schema::create('jobdates', function (Blueprint $table) {
            $table->id();
            $table->bigInteger('jobad_id', [])->unsigned();
            $table->date('date', []);
            $table->string('insertiontime', 255, []);
            $table->timestamp('created_at', [])->nullable();
            $table->timestamp('updated_at', [])->nullable();
            $table->timestamp('deleted_at', [])->nullable();

            $table
                ->foreign('jobad_id')
                ->references('id')
                ->on('jobads')
                ->onDelete('cascade')
                ->onUpdate('cascade');
        });
 }

Update from Vemto:
public function up()
    {
        Schema::table('jobdates', function (Blueprint $table) {
            $table
                ->bigInteger('jobad_id', [])
                ->unsigned()
                ->autoIncrement()
                ->index()
                ->change();
        });
    }

**Comment by madesole** [comment]
I am using Vemto 2.0.21 Alpha.  The project was newly created with Vemto (Filament, Jetstream, Teams, TailwindCSS) and runs during development on Windows with Laragon 6.0 (PHP 8.2.20, Mysql 8.030, Apache 2.459).

**Comment by TiagoSilvaPereira** [comment]
@madesole could you please check if 2.0.22 fixes your issue?

**Comment by madesole** [comment]
The autoincrement now works. But now I have a new problem.

TypeError: Cannot read properties of null (reading 'unique')
    at Proxy.implicitUniqueWasRemoved (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.796550c1.js:115:51963)
    at file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.796550c1.js:115:67054
    at Array.filter (<anonym>)
    at Proxy.getColumnsWithRemovedUnique (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.796550c1.js:115:67042)
    at Object.eval (eval at compileAsync (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.796550c1.js:318:649), <anonymous>:518:32)
    at kae.compileAsync (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.796550c1.js:318:675)
    at kae.compileAsyncWithErrorTreatment (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.796550c1.js:318:290)
    at Wy.compile (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.796550c1.js:364:14378)
    at Wy.compileWithImports (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.796550c1.js:364:13975)
    for async Hpe.generateUpdaterMigration (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.796550c1.js:1155:146506)
In line 361 of the template (anonymous template)
358
            <# #>
359
            <# #>
360
            <# Columns that have changed the unique status from true to false #>
361
            <% for (let column of this.table.getColumnsWithRemovedUnique()) { %>
362
                $table->dropUnique(['<$ column.name $>']);
363
            <% } %>
364
            <# #>

**Comment by madesole** [comment]
With the update 2.23 it works again. Thank you!

**Comment by TiagoSilvaPereira** [comment]
@madesole perfect
