### ISSUE TITLE
Filament unexpected fully qualified name

### ISSUE THREAD

**Issue by khalidmaquilang** [VemtoOrg/vemto2-issues#172]
When I set Route base path either blank or '/' it returns 
`schema-reader-mg Error: syntax error, unexpected fully qualified name "\StudentResource\Pages", expecting "{"`

<img width="1384" alt="Screenshot 2024-06-29 at 6 21 14 PM" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/120788000/6e94b953-c064-4ce2-86e1-e1a589aa3954">

**Comment by TiagoSilvaPereira** [comment]
Hi @khalidmaquilang could you please check if there are syntax issues in the generated file?

**Comment by khalidmaquilang** [comment]
> Hi @khalidmaquilang could you please check if there are syntax issues in the generated file?

There is.. imports became like this `<path>//StudentResource/Pages`

**Comment by TiagoSilvaPereira** [comment]
Could you please send some prints of the problematic files?

**Comment by khalidmaquilang** [comment]
<img width="599" alt="Screenshot 2024-07-02 at 2 45 21 PM" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/120788000/3e1e309f-fcc9-4852-bfaf-67f714593e5e">
<img width="626" alt="Screenshot 2024-07-02 at 2 45 26 PM" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/120788000/4ebbf1f6-09b1-4a58-ab3a-2bff8f643d10">
<img width="604" alt="Screenshot 2024-07-02 at 2 45 29 PM" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/120788000/e3352fbc-9bb9-4fba-9e3b-ea68367b2236">
<img width="624" alt="Screenshot 2024-07-02 at 2 45 33 PM" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/120788000/927a22a1-3723-481b-882f-d83eb70409b8">
<img width="610" alt="Screenshot 2024-07-02 at 2 45 36 PM" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/120788000/9ff82547-ea1a-425b-8872-5c6a6f603c58">

![Screenshot 2024-07-02 at 2 45 45 PM](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/120788000/d831c4e9-152c-4c2c-b11a-cabfb832c0bc)

these are the images

EDIT:
I forgot to take a screenshot for the filament resource in the Application Tab

**Comment by TiagoSilvaPereira** [comment]
It seems you removed the base path. It is necessary to compose the namespace:

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/34b9ff5d-398e-4e8e-9ced-7c1429db9b7f)

**Comment by khalidmaquilang** [comment]
> It seems you removed the base path. It is necessary to compose the namespace:
> 
> ![image](https://private-user-images.githubusercontent.com/11933789/345068311-34b9ff5d-398e-4e8e-9ced-7c1429db9b7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MzAxNTksIm5iZiI6MTcxOTkyOTg1OSwicGF0aCI6Ii8xMTkzMzc4OS8zNDUwNjgzMTEtMzRiOWZmNWQtMzk4ZS00ZThlLTljZWQtN2MxNDI5ZGI5YjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDE0MTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmN2NiODVjYmRmODc5ZDE3YTFhOTk4MTdhNjU5MzE2ZjU0NjM1ZWUwOGQ0ODk5YzljMzY1MjQxYWVjZTYwMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gd9EpWhPtxkgl3m7rIRilv_WcdUkUfLt_N4EYabJ1ek)

Yes.. it should be allowed since I don't want to have a base path..

**Comment by TiagoSilvaPereira** [comment]
I understand, but for now, it is not possible. I'll annotate this as a suggestion

**Comment by khalidmaquilang** [comment]
Thank you so much! I really love your app especially the database design part..

**Comment by TiagoSilvaPereira** [comment]
Added to the Backlog
