### ISSUE TITLE
Trait "Laravel\Sanctum\HasApiTokens" not found

### ISSUE THREAD

**Issue by zerocool-network** [VemtoOrg/vemto2-issues#174]
**Error Message:**
(error) FAILED to execute command: "php" -d display_errors=on "/Applications/Vemto.app/Contents/Resources/static/VMTTL2"
    |> 
Fatal error: Trait "Laravel\Sanctum\HasApiTokens" not found in /Volumes/zerocool/Backup/Proyectos/Clientes/Expansiva/expansiva_2/app/Models/User.php on line 13

**Stack:**
```
Error: Command failed: "php" -d display_errors=on "/Applications/Vemto.app/Contents/Resources/static/VMTTL2"

    at ChildProcess.exithandler (node:child_process:407:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

---

Vemto 2.0.23
darwin 23.5.0
Locale: es
App version: 2.0.23

**Comment by TiagoSilvaPereira** [comment]
Hi @zerocool-network is this a new Vemto 2 project? Is Laravel Sanctum installed? Seems you are trying to use Laravel Sanctum on your project but it seems not to be installed

**Comment by TiagoSilvaPereira** [comment]
Closing due to lack of details (it seems not to be a Vemto issue)
