### ISSUE TITLE
schema-reader-db Error: DB connection failed: could not find driver

### ISSUE THREAD

**Issue by Elisha51** [VemtoOrg/vemto2-issues#182]
**Error Message:**
schema-reader-db Error: DB connection failed: could not find driver

**Stack:**
```
schema-reader-db Error: #0 phar:///tmp/.mount_Vemto-klbnUB/resources/static/VMTTL2/src/DatabaseManager.php(20): VemtoDBReader\DatabaseManager->connect()
#1 phar:///tmp/.mount_Vemto-klbnUB/resources/static/VMTTL2/index.php(94): VemtoDBReader\DatabaseManager->__construct()
#2 phar:///tmp/.mount_Vemto-klbnUB/resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#3 phar:///tmp/.mount_Vemto-klbnUB/resources/static/VMTTL2/index.php(20): Vemto\Vemto::execute()
#4 /tmp/.mount_Vemto-klbnUB/resources/static/VMTTL2(15): require('...')
#5 {main}
```

---

Vemto 2.1.0
linux 6.9.9-200.fc40.x86_64
Locale: en-US
App version: 2.1.0

**Comment by TiagoSilvaPereira** [comment]
Hi @Elisha51 was the database service running? Could you please check if all extensions required by Vemto are installed?

**Comment by Elisha51** [comment]
would help outline the extensions because I installed the most of them

**Comment by TiagoSilvaPereira** [comment]
@Elisha51 Hi, you can see all the necessary extensions on Vemto's home page.

![image](https://github.com/user-attachments/assets/87aca449-9422-41e0-bd7f-488d6af98bb3)

I'm closing for now, but please feel free to reopen if necessary
