### ISSUE TITLE
(error) FAILED to execute command: composer create-project laravel/laravel:^11.0     

### ISSUE THREAD

**Issue by TubaxCrypter** [VemtoOrg/vemto2-issues#184]
**Error Message:**
(error) FAILED to execute command: composer create-project laravel/laravel:^11.0 BManage
    |> You are running Composer with SSL/TLS protection disabled.
Creating a "laravel/laravel:11.0" project at "./BManage"
Installing laravel/laravel (v11.0.0)
  - Downloading laravel/laravel (v11.0.0)
  - Installing laravel/laravel (v11.0.0): Extracting archive
Created project in C:\Users\Admin\Documents\Bmanage\BManage
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/laravel-ignition[2.4.0, ..., 2.8.0] require ext-curl * -> it is missing from your system. Install or enable PHP's curl extension.
    - Root composer.json requires spatie/laravel-ignition ^2.4 -> satisfiable by spatie/laravel-ignition[2.4.0, ..., 2.8.0].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\php\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-curl` to temporarily ignore these required extensions.

**Stack:**
```
Error: Command failed: composer create-project laravel/laravel:^11.0 BManage
You are running Composer with SSL/TLS protection disabled.
Creating a "laravel/laravel:11.0" project at "./BManage"
Installing laravel/laravel (v11.0.0)
  - Downloading laravel/laravel (v11.0.0)
  - Installing laravel/laravel (v11.0.0): Extracting archive
Created project in C:\Users\Admin\Documents\Bmanage\BManage
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/laravel-ignition[2.4.0, ..., 2.8.0] require ext-curl * -> it is missing from your system. Install or enable PHP's curl extension.
    - Root composer.json requires spatie/laravel-ignition ^2.4 -> satisfiable by spatie/laravel-ignition[2.4.0, ..., 2.8.0].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\php\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-curl` to temporarily ignore these required extensions.

    at ChildProcess.exithandler (node:child_process:407:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

---

Vemto 2.1.0
win32 10.0.22631
Locale: tr
App version: 2.1.0

**Comment by TiagoSilvaPereira** [comment]
@TubaxCrypter please install all necessary extensions before creating a new project 

![image](https://github.com/user-attachments/assets/659a0fb1-0f36-479c-b9d6-3227bf0fd51d)
