### ISSUE TITLE
custom code gets overwritten by vemto

### ISSUE THREAD

**Issue by ankorinek** [VemtoOrg/vemto2-issues#195]
I have some custom code I need to add to relationship manager files. In the vemto.app the code tab editors seem to be all readonly. When I edit the file externally, the change is not being picked up externally. Vemto overwrites my changes and marks them as conflict. I manually resolve the conflict, adding my custom code back in, but this gets again reverted next time I generate the code in vemto.

**Comment by TiagoSilvaPereira** [comment]
Hi @ankorinek, you can add custom code inside the code hooks:

![image](https://github.com/user-attachments/assets/dd63e967-635f-4f23-b8cb-dfaafdc9d558)

Just so you know, Vemto finds it challenging to detect code that was added internally (that is why we have the option to manage conflicts). A tip is to keep making changes inside Vemto until you are satisfied, and then you can resolve the code conflict (you do not need to resolve the code conflict every time you generate code). 

I want to let you know that Vemto won't overwrite your changed file unless you explicitly permit it via the conflict resolution screen (even if you generate code numerous times).

If code hooks and conflict resolution don't work for your case, you can instruct Vemto to ignore some files:

![image](https://github.com/user-attachments/assets/caf297ce-073e-47de-9306-eb1b3712ae6d)
