### ISSUE TITLE
Application name must be statically named Vemto

### ISSUE THREAD

**Issue by MikeCraig418** [VemtoOrg/vemto2-issues#2]
**OS:** Mac M1

Originally, I had named "Vemto" as "Vemto 2" to keep my original vemto install.

![](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/23151962/a8dd6e90-dc85-4729-8430-729888c54e55)

Running the application as "Vemto 2" throws an error in the main console:

![](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/23151962/2a7050d7-8589-4b2d-acdc-cd9f0ff7df05)

**Comment by TiagoSilvaPereira** [comment]
@yo-mike thanks, I'll check this... Would it be possible to install Vemto 2 on another folder (I don't know if this is possible on macOS)

**Comment by MikeCraig418** [comment]
Yes, the binary can be placed in any folder. Generally, on install it's just placed in the Applications folder.

The full path is:

`/Users/yo-mike/Applications` or `~/Applications` 

but of course, it can be placed and launched in any folder.

**Comment by TiagoSilvaPereira** [comment]
@yo-mike I think this problem was already fixed, probably the real problem was the space in the application name. Could you please check if this is still happening with recent Vemto 2 versions?

**Comment by MikeCraig418** [comment]
This is good now :) Thank you
