### ISSUE TITLE
schema-reader-db Error: SQLSTATE[HY000]: General error: 3730 Cannot drop table 'pages' referenced by a foreign key constraint 'page_quiz_page_id_foreign' on table 'page_quiz'. (Connection: vemto_db_connection, SQL: drop table if exists `pages`)

### ISSUE THREAD

**Issue by guerinoj** [VemtoOrg/vemto2-issues#214]
I removed a table and its relation but I have the error below. I can't open my project with Vemto anymore. I tried to drop this table with MySQL from vemto_db_connection but it didn't work

**Error Message:**
schema-reader-db Error: SQLSTATE[HY000]: General error: 3730 Cannot drop table 'pages' referenced by a foreign key constraint 'page_quiz_page_id_foreign' on table 'page_quiz'. (Connection: vemto_db_connection, SQL: drop table if exists `pages`)

---

Vemto 2.1.6
darwin 24.0.0
Locale: fr
App version: 2.1.6

**Comment by TiagoSilvaPereira** [comment]
Hi @guerinoj, it is necessary to fix the migrations. Your migrations are trying to create an FK with a removed table.

**Comment by guerinoj** [comment]
Thank you for your help ! The trick works.
