### ISSUE TITLE
Debug Notifications for Multiple Projects

### ISSUE THREAD

**Issue by gdconnect** [VemtoOrg/vemto2-issues#24]
When working on multiple projects, only show errors and logs for the project currently selected.

**Comment by TiagoSilvaPereira** [comment]
@gdconnect sorry I did not understand. Vemto only allow to open one project at time

**Comment by gdconnect** [comment]
Yes, it has one project open at a time, but the debug messages linger when you switch to a different project. Would be good to clear the debug messages when a new project is loaded.

**Comment by TiagoSilvaPereira** [comment]
@gdconnect Ahh perfect, thanks!!

**Comment by TiagoSilvaPereira** [comment]
Fixed, coming on next version
