### ISSUE TITLE
It keeps modifying my app.blade.php (layout)

### ISSUE THREAD

**Issue by isaackearl** [VemtoOrg/vemto2-issues#29]
Hello, 

I make a new project and install filament.  I only want to use this to model databases and make filament resources.  It tried to modify my layout file, but since I don't want changes to the front end, I didn't accept or merge the file.  However later I found it made those changes anyway when I saw the changes in git.  

Also I'm on a brand new apple silicon macbook pro, and the application is very laggy for me... this makes it difficult to use.

Lastly, it would be really nice if there were instructions and best practices etc and some guides.  I'm very excited about the project, but I just spent 2 hours playing around with it and couldn't get one thing generated (too laggy) and it kept doing things I didn't expect.. Like I couldn't figure out how to make it generate the filament resources.  It kept making blank views for Create/Edit etc.

**Comment by TiagoSilvaPereira** [comment]
Hello, could you please record a video demonstrating the slowness problem? We've been trying to reproduce the problem for days, but we haven't managed to do it yet, it's running normally on the macOS machine we have here (8gb, m1).

Also, could you please send some examples of how it is generating Filament views?

**Comment by slaanish** [comment]
I am experiencing the same issue it takes 5 seconds to refresh? It sits there doing nothing and then updates the screen.  M3 mac here. This happens all the time, on every page/screen.   Even with a brand new project with nothing in it.

**Comment by slaanish** [comment]
I updated to 2.06 ARM and the freezing issue is resolved.  This project is awesome.  You rock.

**Comment by TiagoSilvaPereira** [comment]
> Hello,
> 
> I make a new project and install filament. I only want to use this to model databases and make filament resources. It tried to modify my layout file, but since I don't want changes to the front end, I didn't accept or merge the file. However later I found it made those changes anyway when I saw the changes in git.
> 
> Also I'm on a brand new apple silicon macbook pro, and the application is very laggy for me... this makes it difficult to use.
> 
> Lastly, it would be really nice if there were instructions and best practices etc and some guides. I'm very excited about the project, but I just spent 2 hours playing around with it and couldn't get one thing generated (too laggy) and it kept doing things I didn't expect.. Like I couldn't figure out how to make it generate the filament resources. It kept making blank views for Create/Edit etc.

@isaackearl I could not reproduce the problem with app layout file. Could you please check if this is stillç happening on version 2.0.7+?

Also, macOS performance issues were already fixed

**Comment by TiagoSilvaPereira** [comment]
@isaackearl is this issue still happening?

**Comment by isaackearl** [comment]
> @isaackearl is this issue still happening?

Unfortunately I haven't had a chance to try it yet.. I'll download the updates and give it a shot sometime soon.

**Comment by TiagoSilvaPereira** [comment]
@isaackearl thanks, I'll close for now as this seems to be fixed. Please feel free to reopen or send a video record to help bug reproduction if necessary
