### ISSUE TITLE
(stderr) FAILED to execute command: "/usr/bin/php"

### ISSUE THREAD

**Issue by lucasvieira2902** [VemtoOrg/vemto2-issues#31]
**Error Message:**
(stderr) FAILED to execute command: "/usr/bin/php" "/tmp/.mount_Vemto-w36bNw/resources/static/VMTTL1"

PHP Warning:  require(/home/lucas/code/bolso-zen/vendor/autoload.php): Failed to open stream: No such file or directory in phar:///tmp/.mount_Vemto-w36bNw/resources/static/VMTTL1/load.php on line 7
PHP Fatal error:  Uncaught Error: Failed opening required '/home/lucas/code/bolso-zen/vendor/autoload.php' (include_path='.:/usr/share/php') in phar:///tmp/.mount_Vemto-w36bNw/resources/static/VMTTL1/load.php:7
Stack trace:
#0 phar:///tmp/.mount_Vemto-w36bNw/resources/static/VMTTL1/index.php(4): require_once()
#1 /tmp/.mount_Vemto-w36bNw/resources/static/VMTTL1(15): require('...')
#2 {main}
  thrown in phar:///tmp/.mount_Vemto-w36bNw/resources/static/VMTTL1/load.php on line 7

**Stack:**
```
null
```

---

Vemto 2.0.5
linux 6.5.0-25-generic
Locale: pt-BR
App version: 2.0.5

**Comment by TiagoSilvaPereira** [comment]
@LucasVieira2902 It seems the problem, in this case, is that the composer's /vendor folder was not present. Please try composer install and connect again (recent Vemto versions will alert you if the /vendor folder does not exist)
