### ISSUE TITLE
Column name clearing out

### ISSUE THREAD

**Issue by MeisamMulla** [VemtoOrg/vemto2-issues#34]
When attempting to create a column with a name that is an extension of an existing one, Vemto currently erases the new name if it detects any match with the existing names, regardless of the additional characters added. This behavior disrupts the ability to efficiently name columns in a related series or with hierarchical significance.

To enhance user experience and allow for more flexibility in naming conventions, I suggest modifying the current real-time validation method. Instead of actively monitoring and validating the column name as it is being typed, it may be more practical to implement a validation check that triggers upon the user moving focus away from the input field. This approach could reduce the likelihood of inadvertent name removals and support a more seamless column naming process.

https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1777638/5fa6e3e0-f3ad-43e1-a70d-bb49088a4512

**Comment by TiagoSilvaPereira** [comment]
@MeisamMulla thanks for reporting, I'll fix this bug soon

**Comment by TheITJuggler** [comment]
This is similar to [Issue 14](https://github.com/TiagoSilvaPereira/vemto2-issues/issues/14)

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.0.7
