### ISSUE TITLE
Can't connect folder for existing projects (Windows)

### ISSUE THREAD

**Issue by OrakFR** [VemtoOrg/vemto2-issues#39]
Using Vemto 2.0.5 on Windows and can't connect to folders on existing projects. It throws an error
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/129159551/7a280764-4c47-421c-aa4f-55a85e79c139)

but no logs or errors are displayed
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/129159551/e2271b0a-df07-4ace-a803-29b251362a95)

Meanwhile, there's no problem connecting to folder when it's a new application.

**Comment by TiagoSilvaPereira** [comment]
@OrakFR I'm working o a new schema reader for existing Laravel projects

**Comment by OrakFR** [comment]
Cool, looking forward to it then!!!

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.0.7 by using the new Database Schema Reader mode
