### ISSUE TITLE
Livewire file are being added to project even though Has Livewire installed is NOT checked

### ISSUE THREAD

**Issue by waw3** [VemtoOrg/vemto2-issues#44]
Vemto 2.0.5

css Framework: Bootstrap
Starter Kit: Laravel UI
its a fresh laravel project is checked 

Once project is connected .. i just add the user crud and then click generate code

as you can see the files wjere added to app/Livewire and in the routes
![Screenshot 2024-03-22 at 8 23 20 AM](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/7088110/6960fe04-5503-4886-a03b-1edf09b30d6d)

when i delete the folder from the app/Livewire folder and re-run generate code .. it gets added back

note** i do have a pervious project added before this one and when i open tht project and run generate code NO app/Livewire files are added

**Comment by TiagoSilvaPereira** [comment]
@waw3 The "Has Livewire installed" checkbox tells Vemto that Livewire is or is not installed (I'll probably remove this soon as Vemto can now detect this automatically). 

The Vemto CRUD is still generated with Livewire (there is only Livewire and Filament options for now), so if you want to use CRUD features, it is necessary to install Livewire (next Vemto version will install it automatically)
