### ISSUE TITLE
Problem with setting php path while using Herd

### ISSUE THREAD

**Issue by Spyabo** [VemtoOrg/vemto2-issues#47]
**Error Message:**
(stderr) FAILED to execute command: "./Users/reese/Library/Application\ Support/Herd/bin/php83" "/private/var/folders/ws/hnj0j65x7f19srn_3c3_nzw00000gn/T/AppTranslocation/AC520167-C206-4162-B6D7-F90C5D3266B9/d/Vemto.app/Contents/Resources/static/VMTTL1"

/bin/sh: ./Users/reese/Library/Application\ Support/Herd/bin/php83: No such file or directory

**Stack:**
```
null
```

---

Vemto 2.0.5
darwin 22.6.0
Locale: en-GB
App version: 2.0.5

**Comment by TiagoSilvaPereira** [comment]
@Spyabo seems this is a relative path... please use the absolute path. Also please try to remove unnecessary (\ Support) spaces and incorrect slashes (/ with \, etc)
