### ISSUE TITLE
The folder “resources” can’t be opened because you don’t have permission to see its contents.

### ISSUE THREAD

**Issue by martin-arvisais** [VemtoOrg/vemto2-issues#52]
<img width="592" alt="image" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/43321941/ca784ffb-d760-4ef7-8e6c-b2b765625c22">

On MBP M1Pro Silicon. PHP 8.3
First run of a brand new project.

<img width="835" alt="image" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/43321941/377c66c6-ca53-48fd-b8a6-3e55857bdea3">

**Comment by TiagoSilvaPereira** [comment]
@martin-arvisais was the project created with Vemto or manually?

**Comment by TiagoSilvaPereira** [comment]
Hi @martin-arvisais is this still happening?

**Comment by TiagoSilvaPereira** [comment]
Closing. We'll continue the discussion on issue #97
