### ISSUE TITLE
Unable to create "New App"

### ISSUE THREAD

**Issue by TheITJuggler** [VemtoOrg/vemto2-issues#58]
Vemto 2.0.6 - "/Applications/Vemto 2"
Macbook Pro 2021 - M1 - Sonoma 14.4.1
Vemto 1.3.3 - "/Applications/vemto"

Issue: Unable to create new Laravel application through Vemto 2.0.6 interface.

After confirming the location of composer:
![Screenshot 2024-04-04 at 09 22 37](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1438462/a1a78352-cef2-4853-881c-c9b342687c2d)

After adding into Vemto 2.0.6 setting via "cog" icon:
<img width="702" alt="Screenshot 2024-04-04 at 09 22 19" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1438462/f79c9790-ba24-4e73-a61b-b7c23ed657db">

After clicking on "New App":
<img width="431" alt="Screenshot 2024-04-04 at 09 23 08" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1438462/6b1f4a72-199d-416d-a6cb-63c0f2356774">

Also confirmed that $PATH is correct:
![Screenshot 2024-04-04 at 09 29 17](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1438462/355fd619-581f-435e-ae24-5170bd2a6b42)

Confirmed there is no 'composer' in the Rancher Desktop folder (/Users/stephen.ollis/.rd) to exclude a faulty "composer" application firing up:
![Screenshot 2024-04-04 at 09 33 29](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1438462/2bebb674-623b-4bad-be63-a610ef108a22)

**Comment by TiagoSilvaPereira** [comment]
Hi @TheITJuggler is composer accessible globally? If yes, you can try removing the composer path, as Vemto can detect globally installed composer and php

**Comment by TiagoSilvaPereira** [comment]
Also, what is returned when you execute:

```
which composer
```

on your CLI?

**Comment by TheITJuggler** [comment]
which composer:

![Screenshot 2024-04-04 at 12 08 47](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1438462/743ca8db-63c6-457b-b41e-eb4cc2f2c8c9)

Removing the composer setting returns the same error.

**Comment by TiagoSilvaPereira** [comment]
Hi @TheITJuggler could you please check 2.0.7?

**Comment by TheITJuggler** [comment]
Confirmed resolved in 2.0.7.
