### ISSUE TITLE
No Scroll on Validation Screen

### ISSUE THREAD

**Issue by timlalev** [VemtoOrg/vemto2-issues#60]
Caught a small UI bug. On the validation screen when the model has a lot of columns I can't scroll down to edit the rules
<img width="1492" alt="Screenshot_2024-03-17_at_3 24 13_AM" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11634736/4a4f7786-946a-482f-84f8-c542cb983cea">

**Comment by TiagoSilvaPereira** [comment]
@timlalev thanks for reporting, I'll solve this

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.0.12
