### ISSUE TITLE
Incorrect Multi Word Filament Resource Path

### ISSUE THREAD

**Issue by timlalev** [VemtoOrg/vemto2-issues#61]
Whenever a multi word table name and/or model is used for filament resource the file path throws errors upon code generation because it adds empty spaces.

Example: 
- table "lead_lists" 
- model "LeadList"

Generating Filament Resource for "LeadList" produces those errors:

<img width="1131" alt="Screenshot 2024-04-05 at 4 20 24 PM" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11634736/5869d80d-5866-42cb-9b0d-d534227f0280">

I found that by editing the "Name" and "Plural" values inside the Filament Application Settings we can fix the issue by removing the empty space.

<img width="1489" alt="Screenshot 2024-04-05 at 4 32 48 PM" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11634736/3840a409-fa49-48ee-a454-1757451b09cf">

**Comment by nicollassilva** [comment]
HI @timlalev Thank you for the report! This will be fixed soon.

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.0.7
