### ISSUE TITLE
(error) FAILED to execute command: "php" "/Applications/Vemto.app/Contents/Resources/static/VMTTL2"

### ISSUE THREAD

**Issue by turkialawlqy** [VemtoOrg/vemto2-issues#76]
**Error Message:**
(error) FAILED to execute command: "php" "/Applications/Vemto.app/Contents/Resources/static/VMTTL2"

**Stack:**
```
Error: Command failed: "php" "/Applications/Vemto.app/Contents/Resources/static/VMTTL2"

    at ChildProcess.exithandler (node:child_process:407:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.0.7
darwin 23.4.0
Locale: en-US
App version: 2.0.7

**Comment by TiagoSilvaPereira** [comment]
Hi @turkialawlqy, could you please provide more details? Is this a new project or an existing one? Is PHP installed? What we can do to reproduce this error?

**Comment by turkialawlqy** [comment]
> Hi @turkialawlqy, could you please provide more details? Is this a new project or an existing one? Is PHP installed? What we can do to reproduce this error?

Hi @TiagoSilvaPereira 
I created a new project with version 2.0.6 and it works fine. Then I updated to version 2.0.7, and when I open the project, this problem appears. In fact, I do not know the reason for the appearance of this problem.

**Comment by TiagoSilvaPereira** [comment]
@turkialawlqy does it happen when creating a new project with 2.0.7? Could you also, please test if changing connection settings make it work?

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/d0307248-176c-401a-a869-26e86882596b)

**Comment by turkialawlqy** [comment]
> @turkialawlqy does it happen when creating a new project with 2.0.7? Could you also, please test if changing connection settings make it work?
> 
> ![image](https://private-user-images.githubusercontent.com/11933789/322958963-d0307248-176c-401a-a869-26e86882596b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyOTc4NjMsIm5iZiI6MTcxMzI5NzU2MywicGF0aCI6Ii8xMTkzMzc4OS8zMjI5NTg5NjMtZDAzMDcyNDgtMTc2Yy00MDFhLWE4NjktMjZlODY4ODI1OTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE5NTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYjUyNzY5MjU2YzkwODY0NzI0YWU2Y2M0MWRkMjNmN2YwMzliNTYyY2FkMWM1ZGM4NmNmMTY0Nzk0NmYzNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mCTKqsFR89XFNP_zOL_nPU2qSQTXNdEtco6EezzTBXw)

I think I have found the cause of the problem
I worked on an old project and copied all the old model files
And the old database, as well as the migrations files
And then these problems happened

**Comment by juliangums** [comment]
@TiagoSilvaPereira I had this issue yesterday too, but after the fix you deployed in version 2.0.8 this seems fixed.

**Comment by TiagoSilvaPereira** [comment]
@turkialawlqy could you please confirm 2.0.8 fixes this issue?

**Comment by TiagoSilvaPereira** [comment]
Closing for now, as it seems fixed. Please feel free to reopen
