### ISSUE TITLE
schema-reader Error: #0 (PostgreSQL)

### ISSUE THREAD

**Issue by Claonilton** [VemtoOrg/vemto2-issues#77]
App: Vemto
Version: 2.0.7:
Log and Erros: 
phar://C:/Users/usuario/AppData/Local/Programs/Vemto/resources/static/VMTTL2/index.php(86): VemtoDBReader\DatabaseManager->dropDatabase()
#1 phar://C:/Users/usuario/AppData/Local/Programs/Vemto/resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#2 phar://C:/Users/usuario/AppData/Local/Programs/Vemto/resources/static/VMTTL2/index.php(18): Vemto\Vemto::execute()
#3 C:\Users\usuario\AppData\Local\Programs\Vemto\resources\static\VMTTL2(14): require('...')

Log in server:
db-1                 | 2024-04-16 02:19:15.044 UTC [476] ERROR:  relation "sessions" does not exist at character 15
db-1                 | 2024-04-16 02:19:15.044 UTC [476] STATEMENT:  select * from "sessions" where "id" = $1 limit 1
apache_php-1         | 172.25.0.1 - - [15/Apr/2024:23:19:11 -0300] "GET / HTTP/1.1" 200 3728 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
db-1                 | 2024-04-16 02:21:19.783 UTC [491] ERROR:  syntax error at or near "`" at character 25
db-1                 | 2024-04-16 02:21:19.783 UTC [491] STATEMENT:  DROP DATABASE IF EXISTS `vemto_automato`

The error indicates that there is a syntax error in the executed SQL command. In PostgreSQL, identifiers (such as table names or database names) are not enclosed with backticks (`), unlike MySQL. In PostgreSQL, you should use double quotes (") to delimit identifiers when they are case-sensitive or contain special characters. However, if the identifier is entirely in lowercase and does not contain special characters, quotes are not necessary.

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/16517344/5d5a18bc-e2c7-474a-82b3-0b48d11b146e)

**Comment by TiagoSilvaPereira** [comment]
@Claonilton thanks, we'll fix this for postgresql soon

**Comment by TiagoSilvaPereira** [comment]
@Claonilton While Postgres support is not stable, if your project doesn't have special Postgres syntax on migrations, you can use Mysql in Database mode without problems (Vemto can use a different database engine to read the schema if you can handle to run your migrations on it)

**Comment by TiagoSilvaPereira** [comment]
@Claonilton PostgreSQL is now officially supported by Vemto 2.0.10
