### ISSUE TITLE
[BUG]  Vemto 2.0.2 Permission Issues and Windows PowerShell call on Linux OS

### ISSUE THREAD

**Issue by bashman** [VemtoOrg/vemto2-issues#8]
`
node v18.18.2
PHP 8.2.16 (cli)
Ubuntu 23
`
Permission issues:
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1690516/54820d22-334a-46d8-8974-341d04f2b440)

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1690516/c52901f9-6551-453b-ba72-b6dcf3bc656e)

Vemto is calling Powershell on Linux. 

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/1690516/426a34af-955c-4e76-8a40-7943601736d9)

**Comment by TiagoSilvaPereira** [comment]
@bashman if you delete .vemto and reconnect your project, does the permission issues continue happening?

**Comment by bashman** [comment]
> @bashman if you delete .vemto and reconnect your project, does the permission issues continue happening?

As a Linux user, I did that, I deleted the directory and fixed permissions. But nothing happened. It is probably a problem with the AppImage. If you can send to my mail a zip with the binaries of the project without packaging it, I can test.

**Comment by TiagoSilvaPereira** [comment]
@bashman could you please check 2.0.4 regarding this issue? We are using chmod 755 and people reported the issue was gone

**Comment by TiagoSilvaPereira** [comment]
@bashman is permission issue still happening on 2.0.7?

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.0.14
