### ISSUE TITLE
(error) FAILED to execute command: "c:\php\php.exe" "C:\Users\usuario\AppData\Local\Programs\Vemto\resources\static\VMTTL2"

### ISSUE THREAD

**Issue by Claonilton** [VemtoOrg/vemto2-issues#85]
**Error Message:**
(error) FAILED to execute command: "c:\php\php.exe" "C:\Users\usuario\AppData\Local\Programs\Vemto\resources\static\VMTTL2"

**Stack:**
```
Error: Command failed: "c:\php\php.exe" "C:\Users\usuario\AppData\Local\Programs\Vemto\resources\static\VMTTL2"

    at ChildProcess.exithandler (node:child_process:407:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

---

Vemto 2.0.7
win32 10.0.22631
Locale: pt-BR
App version: 2.0.7

**Comment by TiagoSilvaPereira** [comment]
Hi @Claonilton is this a new project or an existing one? Please try closing Vemto and opening it again

**Comment by Claonilton** [comment]
Hi, @TiagoSilvaPereira ... It is a project created on Vemto. There was an error when creating the login, I migrated it, but I had an error reselecting the users table, I'm going to redo the project...

**Comment by TiagoSilvaPereira** [comment]
@Claonilton, would it be possible to record a video showing how to reproduce this problem? Or maybe write down the steps to reproduce it, please?

**Comment by Claonilton** [comment]
The problem occurs when I try to create the relationship between users and teams in VEMTO, because without this link the system does not work.

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/16517344/40f0a71c-3884-4115-841b-02cb21c9e7cf)

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/16517344/7944e259-da87-47fc-9e68-f75b292c3643)

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/16517344/652368a5-b733-4da6-90c2-12b4f77a8c27)

When recreating the project I can't save it and the last time I did it gave the error mentioned.

I can recreate the project, but where do I update the relationship between users and teams?

**Comment by TiagoSilvaPereira** [comment]
@Claonilton thank you for the detailed information. I'll check this

**Comment by TiagoSilvaPereira** [comment]
@Claonilton did you clicked to solve the conlicts in the models section?

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/b049201f-74e1-454e-8190-6fdb48cdc867)

**Comment by TiagoSilvaPereira** [comment]
@Claonilton closing for now as it seems not to be a Bug. Please click to solve the conflicts before saving Schema changes.
