### ISSUE TITLE
schema-reader Error: Method Illuminate\Foundation\Application::configure does not exist.

### ISSUE THREAD

**Issue by alexfleites** [VemtoOrg/vemto2-issues#87]
**Error Message:**
schema-reader Error: Method Illuminate\Foundation\Application::configure does not exist.

**Stack:**
```
schema-reader Error: #0 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(27): Illuminate\Foundation\Application::__callStatic('configure', Array, basePath: 'phar:///Applica...')
#1 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#2 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(18): Vemto\Vemto::execute('schema-reader', Object(Closure))
#3 /Applications/Vemto.app/Contents/Resources/static/VMTTL2(15): require('phar:///Applica...')
#4 {main}
```

---

Vemto 2.0.7
darwin 23.4.0
Locale: en-US
App version: 2.0.7

**Comment by TiagoSilvaPereira** [comment]
Hi @alexfleites is your application Laravel 11? Is Laravel correctly installed? Vemto needs to boot the application, and this method exists only on Laravel 11 apps.

**Comment by alexfleites** [comment]
My application is Laravel 11... I think that the issue is that I am running under docker, LMK is this is an issue for Vemto?

**Comment by TiagoSilvaPereira** [comment]
@alexfleites maybe, I haven't tried Vemto with Docker yet (we have plans to support Docker through SSH, but we are focused on local installations until we reach stability)

**Comment by TiagoSilvaPereira** [comment]
@alexfleites does 2.0.8 solves this problem?

**Comment by alexfleites** [comment]
Thx, I'll let you know

**Comment by alexfleites** [comment]
Now I am working with a local server installed - Laravel Herd
Laravel 11
PHP 8.2

And at the same time I clicked Connect get this error, even without select anything

schema-reader Error: Illuminate\Routing\UrlGenerator::__construct(): Argument #2 ($request) must be of type Illuminate\Http\Request

PD: The body if the error was reported!



Alexander Fleites
w: https://github.com/fcdeveloper 
 

CONFIDENTIALITY NOTICE: The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.

**Comment by TiagoSilvaPereira** [comment]
Hi @alexfleites is this error happening also when you try to run your application? It seems it is not a Vemto error, but an application error (Vemto cannot read a project with errors because it needs to boot the application to read the schema strucutre)

**Comment by TiagoSilvaPereira** [comment]
Closing... discussion on https://github.com/TiagoSilvaPereira/vemto2-issues/issues/92
