### ISSUE TITLE
(error) FAILED to execute command: composer create-project laravel/laravel:^11.0 Vemto_test

### ISSUE THREAD

**Issue by myindexlike** [VemtoOrg/vemto2-issues#88]
**Error Message:**
(error) FAILED to execute command: composer create-project laravel/laravel:^11.0 Vemto_test

**Stack:**
```
Error: spawn /bin/sh ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

---

Vemto 2.0.7
darwin 23.4.0
Locale: en
App version: 2.0.7

**Comment by respodeveloper** [comment]
solution #74 In php.ini added setting for extension - pdo_sqlite

**Comment by TiagoSilvaPereira** [comment]
@myindexlike please check if the solution on #74  solves your issue

**Comment by TiagoSilvaPereira** [comment]
@myindexlike did it work?

**Comment by TiagoSilvaPereira** [comment]
@myindexlike, does it work?
