### ISSUE TITLE
automatic updates

### ISSUE THREAD

**Issue by juliangums** [VemtoOrg/vemto2-issues#89]
In your email it says "Vemto automatically updates to the latest version" but it was never done that for me (perhaps to impatient). Nor can I see where do update manually apart from downloading the newest dmg. I'm on Mac.

**Comment by TiagoSilvaPereira** [comment]
Hi @juliangums, it is due to the way Electron Updater works:

1 - When you open Vemto, and there is a new version, it starts downloading it
2 - After the download, it shows a message asking you to restart to upgrade

I pretend to add a "Downloading new version..." indicator to future versions.
