### ISSUE TITLE
schema-reader Error: Call to a member function compileDisableForeignKeyConstraints() on null

### ISSUE THREAD

**Issue by jjjrmy** [VemtoOrg/vemto2-issues#9]
I get this in my Schema log

**Comment by TiagoSilvaPereira** [comment]
@jjjrmy does this function compileDisableForeignKeyConstraints exists on your code? Seems Vemto cannot read your project due to a problem in the code. Could you please try with a new project and check if the error happens?

**Comment by TiagoSilvaPereira** [comment]
@jjjrmy, does this error keep occurring with 2.0.4?

**Comment by jjjrmy** [comment]
Yes it's still occuring.

I'm not sure where that code exists but we are using `Schema::disableForeignKeyConstraints();` in some migrations, and that looks like it's calling that from within the Laravel framework code.

**Comment by TiagoSilvaPereira** [comment]
> Yes it's still occuring.
> 
> I'm not sure where that code exists but we are using `Schema::disableForeignKeyConstraints();` in some migrations, and that looks like it's calling that from within the Laravel framework code.

Perfect, I'll try to reproduce. Thanks!!

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.0.7 by using Database Schema Reader mode
