### ISSUE TITLE
Can't open Laravel 10 Projects on Vemto 2.0.8 

### ISSUE THREAD

**Issue by MCS-Technology** [VemtoOrg/vemto2-issues#93]
It Say:
Vemto only supports Laravel 11+ projects. Please upgrade your Laravel version before connecting it
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/106679835/00c79d4e-4fd8-4fc5-83be-33c1df355ea2)

I can't upgrade my projets to Laravel 11 for now, i use many package on my projets that not supported by laravel 11 and the new version of PHP, so please let me open old projets on Vemto 2xxx

**Comment by TiagoSilvaPereira** [comment]
Hi @MCS-Technology 

Supporting old versions of Laravel is complex. We have several bugs to fix, and as we are in Alpha, I decided to lock Vemto in Laravel 11 so I can focus on what matters, fixing the bugs and adding new features.

I'm not sure if I'll add the functionality to open old projects in the future. I myself would like to open my old projects in Vemto 2, but the complexity of this task is not trivial.
