### ISSUE TITLE
[Filament] Error field DateTime Picker

### ISSUE THREAD

**Issue by jeffersongoncalves** [VemtoOrg/vemto2-issues#99]
When DateTime Picker is selected as the field type, when generating code it is generating DatetimePicker which is only causing a problem of not finding the filament component.

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/411493/d49fb57c-0c6f-416f-8bba-b539740926ab)
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/411493/358d4d85-5735-4d89-a341-69d435629c19)

**Comment by jeffersongoncalves** [comment]
https://github.com/filamentphp/filament/blob/3.x/packages/forms/src/Components/DateTimePicker.php

**Comment by nicollassilva** [comment]
Hi @jeffersonsimaogoncalves thanks for the report! It will be fixed in the next version.

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.0.11
